# Generated by Django 2.1.8 on 2019-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='limited_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
