# Generated by Django 2.1.8 on 2019-05-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_animal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='defeat_condition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='stare',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='uniq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='victory_condition',
            field=models.TextField(null=True),
        ),
    ]
