# Generated by Django 2.1.8 on 2019-05-12 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190512_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
