# Generated by Django 2.1.8 on 2019-05-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='starve',
            field=models.IntegerField(null=10),
        ),
    ]
