# Generated by Django 2.1.8 on 2019-05-12 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_auto_20190512_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ID',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='starve',
            field=models.IntegerField(default=10),
        ),
    ]
